'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import { store } from './redux/store'
import { Provider } from 'react-redux'
import Menu from './Header/page'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme';
import { parseCookies } from 'nookies'
import { useState, useEffect } from 'react';
import { usePathname } from 'next/navigation'
import { AuthProvider } from './Context/logout'
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  // const pathname = usePathname();
  // const [isLogin, setIsLogin] = useState('');

  // useEffect(() => {
  //   const token = parseCookies()['token'];
  //   setIsLogin(token);
  // }, [pathname]);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <AppRouterCacheProvider options={{ key: 'css' }}>
            <ThemeProvider theme={theme}>
              <AuthProvider>
                {children}
                <ToastContainer
                  toastStyle={{
                    minHeight: '20px',
                    padding: '8px',
                    fontSize: '12px',
                  }}
                  bodyStyle={{
                    margin: 0,
                    padding: 0,
                  }}
                />
              </AuthProvider>
            </ThemeProvider>
          </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
